import nodemailer from 'nodemailer';

export class EmailService {
  private transporter: nodemailer.Transporter;

  constructor() {
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    });
  }

  /**
   * Send daily newsletter email
   */
  async sendNewsletter(to: string, subject: string, htmlContent: string): Promise<boolean> {
    try {
      // Split multiple email addresses by comma
      const recipients = to.split(',').map(email => email.trim()).filter(email => email);
      
      const mailOptions = {
        from: `주식 뉴스레터 <${process.env.EMAIL_USER}>`,
        to: recipients.join(', '),
        subject,
        html: this.wrapInEmailTemplate(htmlContent),
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`뉴스레터가 성공적으로 발송되었습니다: ${recipients.join(', ')}`);
      return true;
    } catch (error) {
      console.error('이메일 발송 중 오류 발생:', error);
      return false;
    }
  }

  /**
   * Wrap content in professional email template
   */
  private wrapInEmailTemplate(content: string): string {
    // Convert markdown to HTML (simple version)
    const htmlContent = this.markdownToHtml(content);

    return `
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background-color: #ffffff;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #1a1a1a;
      border-bottom: 3px solid #4CAF50;
      padding-bottom: 10px;
    }
    h2 {
      color: #2c3e50;
      margin-top: 30px;
      border-left: 4px solid #4CAF50;
      padding-left: 15px;
    }
    h3 {
      color: #34495e;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    th {
      background-color: #f8f9fa;
      font-weight: 600;
      color: #2c3e50;
    }
    .decision-badge {
      display: inline-block;
      padding: 6px 12px;
      border-radius: 4px;
      font-weight: 600;
      color: white;
    }
    .strong-buy { background-color: #28a745; }
    .buy { background-color: #5cb85c; }
    .hold { background-color: #ffc107; color: #333; }
    .sell { background-color: #dc3545; }
    .strong-sell { background-color: #c82333; }
    ul {
      padding-left: 20px;
    }
    li {
      margin: 8px 0;
    }
    hr {
      border: none;
      border-top: 1px solid #e0e0e0;
      margin: 30px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      font-size: 12px;
      color: #666;
      text-align: center;
    }
    .metric-positive {
      color: #28a745;
      font-weight: 600;
    }
    .metric-negative {
      color: #dc3545;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    ${htmlContent}
    <div class="footer">
      <p>본 분석은 정보 제공 목적으로만 제공되며 투자 권유가 아닙니다.</p>
      <p>투자 결정 시 반드시 본인의 판단과 추가 조사를 병행하시기 바랍니다.</p>
      <p style="margin-top: 10px;">Generated by Stock Newsletter AI • ${new Date().toLocaleDateString('ko-KR')}</p>
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Simple markdown to HTML converter
   */
  private markdownToHtml(markdown: string): string {
    let html = markdown;

    // Headers
    html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

    // Bold
    html = html.replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>');

    // Italic
    html = html.replace(/\*(.*?)\*/gim, '<em>$1</em>');

    // Lists
    html = html.replace(/^\- (.*$)/gim, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>');

    // Tables
    html = this.convertTables(html);

    // Line breaks
    html = html.replace(/\n\n/g, '</p><p>');
    html = html.replace(/\n/g, '<br>');

    // Wrap in paragraph
    html = `<p>${html}</p>`;

    // HR
    html = html.replace(/---/g, '<hr>');

    return html;
  }

  /**
   * Convert markdown tables to HTML
   */
  private convertTables(markdown: string): string {
    const tableRegex = /\|(.+)\|\n\|[-:\s|]+\|\n((?:\|.+\|\n?)+)/g;
    
    return markdown.replace(tableRegex, (match, header, rows) => {
      const headers = header.split('|').filter((h: string) => h.trim()).map((h: string) => `<th>${h.trim()}</th>`).join('');
      const rowsHtml = rows.trim().split('\n').map((row: string) => {
        const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td>${c.trim()}</td>`).join('');
        return `<tr>${cells}</tr>`;
      }).join('');
      
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rowsHtml}</tbody></table>`;
    });
  }
}
